### ISSUE TITLE
Unknown project phpmyadmin

### ISSUE THREAD

**Issue by d3haynes** [reinblau/vagrant-docker#1]
Hi,

When I go step by step, after I vagrant up I get this...

![vagrant-docker-error](https://cloud.githubusercontent.com/assets/2005366/18952779/3e899a34-8619-11e6-922e-9520191673d6.jpg)

**Comment by d3haynes** [comment]
@tobiasbaehr any idea why it does not recognize the phpmyadmin project?

**Comment by tobiasbaehr** [comment]
Copy projects.txt.dist to projects.txt
